### ISSUE TITLE
Slow with large data-sets

### ISSUE THREAD

**Issue by zachlysobey** [alexandernst/angular-multi-select#46]
I'm loading 6 of these with ~1400 small objects each, and this makes it pretty unusable. If I get a chance, I'll try to put together a minimal demo, but in my app I'm developing it seems significantly slower than the isteven project version (which itself performs too slowly on this large a dataset).

**Comment by alexandernst** [comment]
This is kiind of expected. My project uses nested templating (which is you it is so easy to just pass a nested object and let the directive transform it). 1400 is a lot, but maybe I can do something... Can you setup a small demo so I can check how much I can improve the directive, please?

**Comment by zachlysobey** [comment]
I appreciate that alexander! Not sure when I'll get a chance to put the demo together however,

I'm working on a dev-spike with [one of your competitors](https://github.com/amitava82/angular-multiselect) at the moment, and might not get a chance to revisit for a few days. I don't need the nesting stuff, so maybe _this_ project is overkill for me?

In any case, I do really like this project and want to help keep it moving forward, so I'll leave it high on my todo list.

**Comment by alexandernst** [comment]
Surely that other project will perform better than mine (as it is now) as it doesn't have nested support. Maybe I could be able to squeeze some performance improvements by lazy loading the nested templates, maybe doing some refactoring. I do need that demo/example anyways, so I'll appreciate it very much ;)

**Comment by zachlysobey** [comment]
Not sure this adequately represents my situation, but maybe of some use:
http://plnkr.co/edit/a6y9RopkTclQuRgkg5FP?p=preview

**Comment by alexandernst** [comment]
I had a quick look at your demo. It takes 1.8s here to load the dropdown (which isn't bad at all, given the fact that you're loading 1000 items!). I think I might be able to squeeze 0.3s from here and there, without major refactoring. Anywhere beyond that, some major changes would be required.

Thank you for the demo!

**Comment by zachlysobey** [comment]
I had problems with the search/filter functionality there too. Maybe that fuzzy string matching is too slow on large data sets?

**Comment by alexandernst** [comment]
You're totally right! Searching is dog slow. I should rethink how that works/should work.

**Comment by alexandernst** [comment]
@zachlysobey I gave this a second thought and I think I might be able to refactor the code in a way that everything will be extremely fast. Of course, I'll need some time to actually get to it...

**Comment by zachlysobey** [comment]
sweet! No promises, but if you wanted to outline the strategy here, I _might_ get a chance to attempt a PR myself if I'm capable.

**Comment by alexandernst** [comment]
The refactor would be huge, but here is the plan.

Right now, the directive accepts a nested objects structure that represents the items in the dropdown. This is extremely inefficient when a lot of items are passed (because of how I'm walking the nested objects).

Instead, after receiving the objects structure, we should flatten the entire data (something like http://underscorejs.org/#flatten). Once flattened, we could scratch the entire nested templates loic (which is also extremely costly and inefficient with lost of items).

Of course, the biggest part of that refactor would be the flat() method that would take the data and transform it. We might ask in SO if there is any other data structure that would fit better this particular case (also, we should keep in mind the searching/filtering). Maybe some sort of b-tree?

Also, some smaller things should be refactored, like for example the show/hide llogic for each element (which right now seeks for the parent/child of each node, etc...).

**Comment by alexandernst** [comment]
Closed by v6. Keep in mind that is a huge rewrite. Docs are still missing, but specs are really nice, so you'll probably be able to work your way out until I finish the docs.
