### ISSUE TITLE
ng-model integration?

### ISSUE THREAD

**Issue by phillipgreenii** [alexandernst/angular-multi-select#80]
Is there a reason why `ng-model` wasn't used instead of the various model inputs? I would think things would become more feature rich by sticking closer to core.  Validation would more standard and could probably solve #79 and #28.

**Comment by alexandernst** [comment]
I don't see how using `ng-model` will fix #28, which is caused because the directive isn't handling the backspace button properly on a blocking call (while searching).

As for #79, I keep failing to see how `ng-model` would help here. This is not a simple input where you can force "something" to be written. This is a complex directive that can't work without an input and an output model, because it just can't write the changes back to the input model.

That is why `ng-model` is not used, just to make everybody understand that the `input-model` doesnt' work as `ng-model`.

Regarding your particular issue (#79), let's keep the talk in there.
