### ISSUE TITLE
Cannot resolve module 'angular-multi-select' 

### ISSUE THREAD

**Issue by Hellowor1d** [alexandernst/angular-multi-select#95]
There was a problem confused me for a long time,when I use "npm install angular-multi-select",It's Ok,it lies in the node_modules folders sliently, but when I use webpack(1.13.0) to require("angular-multi-select") in  ./app/jobModule/indexController.js,the problem  came:

ERROR in ./app/jobModule/indexController.js
Module not found: Error: Cannot resolve module 'angular-multi-select' in D:\work\newbeehive\hive\src\app\jobModule
 @ ./app/jobModule/indexController.js 17:4-35

and I don't konw what the wrong was,beacuse the other directives worked well here with the method I took. pls.

**Comment by alexandernst** [comment]
I have no idea how Webpack works or what is required for this library to be compatible with Webpack.  I'll research when I have some spare time.

**Comment by TamaBaka** [comment]
I think I had this problem too considering my source code says 'angular-multi-select/dist/prod/angular-multi-select' instead of 'angular-multi-select'.

So let me explain the trick that I used: inside of the node_module folder you'll find an angular-multi-select folder if it's installed correctly.  Normally, that would be enough.  But I don't know which configuration file makes it work.  However, I found a different solution after playing around a bit.  While messing around, I discovered that webpack was perfectly happy with calling that folder in node_module a base folder!  So with a bit of folder browsing, I figured out the path to the distributable starting from angular-multi-select...and voila:

**require('angular-multi-select/dist/prod/angular-multi-select')**

```
node_modules
    |
    |
    angular-multi-select
        |
        |
        dist
            |
            |
            prod
                |
                |
                **angular-multi-select.js**
                angular-multi-select.min.js
```

The above should work.

This is pointing at the unminimized source code.  You can replace it with 'angular-multi-select/dist/prod/angular-multi-select.min' if you want to include the uglified version.  I figure since webpack can be configured to uglify after the fact, it's perfectly fine using the uncompressed version.

**Comment by Hellowor1d** [comment]
@TamaBaka :+1: Thank you very much for the long and interesting reply :stuck_out_tongue_winking_eye:
